### ISSUE TITLE
ROS autopilot.py

### ISSUE THREAD

**Issue by soldierofhell** [avncalst/drone_cnn#1]
Hi ,
Really nice work! 
Got some comments to ROS autopilot.py:
* you're loading network graph in each callback (cv2.dnn.readNetFromTensorflow). IMO should be done once
* wouldn't be better to use mavros?

Regards,

**Comment by avncalst** [comment]
Thx for your remark. 

- I will correct the loading of the network graph. 

- mavros might be better. So far all my AI work on my drone is done with dronekit, so I kept this approach in the present Sitl project.
